<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class Sale extends Model
{
    use HasFactory, Notifiable, HasApiTokens, HasRoles;

    protected $fillable = [
        'invoice_number', //autogenerated
        'user_id', //background ID
        'subtotal',
        'discount',
        'tax',
        'total',
        'payment_type',
        'amount_tendered',
        'change_due',
        'status',
        'notes',
    ];

    // Define relationship to user
    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

     // Define relationship to sale per item
    public function sale_item()
    {
        return $this->hasMany(SaleItem::class, 'sale_id');
    }
}
